spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
EQT_CLIENT:
  BASE_URL: https://eqtgroup.com
  PORTFOLIO_URL: /page-data/current-portfolio/page-data.json
  DIVESTMENT_URL: /page-data/current-portfolio/divestments/page-data.json


